/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package spc.edu;

import javax.swing.JOptionPane;

/**
 *
 * @author SPC
 */
public class Tictacte extends javax.swing.JFrame {

    /**
     * Creates new form Tictacte
     */
    int turn = 2;
    int buttonused[]={0,0,0,0,0,0,0,0,0};
    
    int PXwon[]={0,0,0,0,0,0,0,0,0};
    int POwon[]={0,0,0,0,0,0,0,0,0};
    
    int PXwon()
    {
        if(PXwon[0]==1 && PXwon[1]==1 && PXwon[2]==1 )
        {
            return 1;
        }
        if(PXwon[3]==1 && PXwon[4]==1 && PXwon[5]==1 )
        {
            return 1;
        }
        if(PXwon[6]==1 && PXwon[7]==1 && PXwon[8]==1 )
        {
            return 1;
        }
        if(PXwon[0]==1 && PXwon[3]==1 && PXwon[6]==1 )
        {
            return 1;
        }
        if(PXwon[1]==1 && PXwon[4]==1 && PXwon[7]==1 )
        {
            return 1;
        }
        if(PXwon[2]==1 && PXwon[5]==1 && PXwon[8]==1 )
        {
            return 1;
        }
        if(PXwon[2]==1 && PXwon[4]==1 && PXwon[6]==1 )
        {
            return 1;
        }
        if(PXwon[0]==1 && PXwon[4]==1 && PXwon[8]==1 )
        {
            return 1;
        }
        return 0 ;
        
    }
    
    
    int POwon()
    {
        if(POwon[0]==1 && POwon[1]==1 && POwon[2]==1 )
        {
            return 1;
        }
        if(POwon[3]==1 && POwon[4]==1 && POwon[5]==1 )
        {
            return 1;
        }
        if(POwon[6]==1 && POwon[7]==1 && POwon[8]==1 )
        {
            return 1;
        }
        if(POwon[0]==1 && POwon[3]==1 && POwon[6]==1 )
        {
            return 1;
        }
        if(POwon[1]==1 && POwon[4]==1 && POwon[7]==1 )
        {
            return 1;
        }
        if(POwon[2]==1 && POwon[5]==1 && POwon[8]==1 )
        {
            return 1;
        }
        if(POwon[2]==1 && POwon[4]==1 && POwon[6]==1 )
        {
            return 1;
        }
        if(POwon[0]==1 && POwon[4]==1 && POwon[8]==1 )
        {
            return 1;
        }
        return 0 ;
    }
    
    
    public Tictacte() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        b3 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b0 = new javax.swing.JButton();
        b8 = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        bnt_1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        b3.setFont(new java.awt.Font("SFU Clearface", 0, 24)); // NOI18N
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });

        b4.setFont(new java.awt.Font("SFU Clearface", 0, 24)); // NOI18N
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });

        b5.setFont(new java.awt.Font("SFU Clearface", 0, 24)); // NOI18N
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });

        b0.setFont(new java.awt.Font("SFU Clearface", 0, 24)); // NOI18N
        b0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b0ActionPerformed(evt);
            }
        });

        b8.setFont(new java.awt.Font("SFU Clearface", 0, 24)); // NOI18N
        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });

        b7.setFont(new java.awt.Font("SFU Clearface", 0, 24)); // NOI18N
        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });

        b1.setFont(new java.awt.Font("SFU Clearface", 0, 24)); // NOI18N
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        b2.setFont(new java.awt.Font("SFU Clearface", 0, 24)); // NOI18N
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });

        b6.setFont(new java.awt.Font("SFU Clearface", 0, 24)); // NOI18N
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setText("Chương Trình Game Cờ Caro X O");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));

        bnt_1.setBackground(new java.awt.Color(0, 204, 204));
        bnt_1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        bnt_1.setText("Play Again ");
        bnt_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnt_1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(70, 70, 70))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(b0, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(b7, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(b8, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(bnt_1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b0, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b8, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b7, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bnt_1)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b0ActionPerformed
        if(buttonused[0]==0){
            
        
        if(turn %2 == 0)
        {
            turn++;
            b0.setText("x");
            buttonused[0]=1;
            PXwon[0]=1;
            
            int result1=PXwon();
            int result2=POwon();
            
            if(result1==1)
            {
                JOptionPane.showConfirmDialog(rootPane, "Nguoi choi X thang !! ");
            }
            else if(result2==1) 
            {
                JOptionPane.showConfirmDialog(rootPane, "Nguoi choi O thang !! ");
            }
        }
        else 
        {
            turn++;
            b0.setText("0");
            buttonused[0]=1;
            POwon[0]=1;
            
            int result1=PXwon();
            int result2=POwon();
            
            if(result1==1)
            {
                JOptionPane.showConfirmDialog(rootPane, "Nguoi choi X thang !! ");
            }
            else if(result2==1) 
            {
                JOptionPane.showConfirmDialog(rootPane, "Nguoi choi O thang !! ");
            }
        }
}


        else{
                JOptionPane.showConfirmDialog(rootPane, "Nút Này Đã sử dụng rồi !!");
                }
        
                
                
    }//GEN-LAST:event_b0ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        if(buttonused[1]==0){
            
        
        if(turn %2 == 0)
        {
            turn++;
            b1.setText("x");
            buttonused[1]=1;
            PXwon[1]=1;
            
            int result1=PXwon();
            int result2=POwon();
            
            if(result1==1)
            {
                JOptionPane.showConfirmDialog(rootPane, "Nguoi choi X thang !! ");
            }
            else if(result2==1) 
            {
                JOptionPane.showConfirmDialog(rootPane, "Nguoi choi O thang !! ");
            }
        }
        else 
        {
            turn++;
            b1.setText("0");
            buttonused[1]=1;
            POwon[1]=1;
            
            int result1=PXwon();
            int result2=POwon();
            
            if(result1==1)
            {
                JOptionPane.showConfirmDialog(rootPane, "Nguoi choi X thang !! ");
            }
            else if(result2==1) 
            {
                JOptionPane.showConfirmDialog(rootPane, "Nguoi choi O thang !! ");
            }
        }
}


        else{
                JOptionPane.showConfirmDialog(rootPane, "Nút Này Đã sử dụng rồi !!");
                }
    }//GEN-LAST:event_b1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        if(buttonused[2]==0){
            
        
        if(turn %2 == 0)
        {
            turn++;
            b2.setText("x");
            buttonused[2]=1;
            PXwon[2]=1;
            
            int result1=PXwon();
            int result2=POwon();
            
            if(result1==1)
            {
                JOptionPane.showConfirmDialog(rootPane, "Nguoi choi X thang !! ");
            }
            else if(result2==1) 
            {
                JOptionPane.showConfirmDialog(rootPane, "Nguoi choi O thang !! ");
            }
        }
        else 
        {
            turn++;
            b2.setText("0");
            buttonused[2]=1;
            POwon[2]=1;
            
            int result1=PXwon();
            int result2=POwon();
            
            if(result1==1)
            {
                JOptionPane.showConfirmDialog(rootPane, "Nguoi choi X thang !! ");
            }
            else if(result2==1) 
            {
                JOptionPane.showConfirmDialog(rootPane, "Nguoi choi O thang !! ");
            }
        }
}


        else{
                JOptionPane.showConfirmDialog(rootPane, "Nút Này Đã sử dụng rồi !!");
                }
    }//GEN-LAST:event_b2ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
       if(buttonused[3]==0){
            
        
        if(turn %2 == 0)
        {
            turn++;
            b3.setText("x");
            buttonused[3]=1;
            PXwon[3]=1;
            
            int result1=PXwon();
            int result2=POwon();
            
            if(result1==1)
            {
                JOptionPane.showConfirmDialog(rootPane, "Nguoi choi X thang !! ");
            }
            else if(result2==1) 
            {
                JOptionPane.showConfirmDialog(rootPane, "Nguoi choi O thang !! ");
            }
        }
        else 
        {
            turn++;
            b3.setText("0");
            buttonused[3]=1;
            POwon[3]=1;
            
            int result1=PXwon();
            int result2=POwon();
            
            if(result1==1)
            {
                JOptionPane.showConfirmDialog(rootPane, "Nguoi choi X thang !! ");
            }
            else if(result2==1) 
            {
                JOptionPane.showConfirmDialog(rootPane, "Nguoi choi O thang !! ");
            }
        }
}


        else{
                JOptionPane.showConfirmDialog(rootPane, "Nút Này Đã sử dụng rồi !!");
                }
    }//GEN-LAST:event_b3ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        if(buttonused[4]==0){
            
        
        if(turn %2 == 0)
        {
            turn++;
            b4.setText("x");
            buttonused[4]=1;
            PXwon[4]=1;
            
            int result1=PXwon();
            int result2=POwon();
            
            if(result1==1)
            {
                JOptionPane.showConfirmDialog(rootPane, "Nguoi choi X thang !! ");
            }
            else if(result2==1) 
            {
                JOptionPane.showConfirmDialog(rootPane, "Nguoi choi O thang !! ");
            }
        }
        else 
        {
            turn++;
            b4.setText("0");
            buttonused[4]=1;
            POwon[4]=1;
            
            int result1=PXwon();
            int result2=POwon();
            
            if(result1==1)
            {
                JOptionPane.showConfirmDialog(rootPane, "Nguoi choi X thang !! ");
            }
            else if(result2==1) 
            {
                JOptionPane.showConfirmDialog(rootPane, "Nguoi choi O thang !! ");
            }
        }
}


        else{
                JOptionPane.showConfirmDialog(rootPane, "Nút Này Đã sử dụng rồi !!");
                }
    }//GEN-LAST:event_b4ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
       if(buttonused[5]==0){
            
        
        if(turn %2 == 0)
        {
            turn++;
            b5.setText("x");
            buttonused[5]=1;
            PXwon[5]=1;
            
            int result1=PXwon();
            int result2=POwon();
            
            if(result1==1)
            {
                JOptionPane.showConfirmDialog(rootPane, "Nguoi choi X thang !! ");
            }
            else if(result2==1) 
            {
                JOptionPane.showConfirmDialog(rootPane, "Nguoi choi O thang !! ");
            }
        }
        else 
        {
            turn++;
            b5.setText("0");
            buttonused[5]=1;
            POwon[5]=1;
            
            int result1=PXwon();
            int result2=POwon();
            
            if(result1==1)
            {
                JOptionPane.showConfirmDialog(rootPane, "Nguoi choi X thang !! ");
            }
            else if(result2==1) 
            {
                JOptionPane.showConfirmDialog(rootPane, "Nguoi choi O thang !! ");
            }
        }
}


        else{
                JOptionPane.showConfirmDialog(rootPane, "Nút Này Đã sử dụng rồi !!");
                }
    }//GEN-LAST:event_b5ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
        if(buttonused[6]==0){
            
        
        if(turn %2 == 0)
        {
            turn++;
            b6.setText("x");
            buttonused[6]=1;
            PXwon[6]=1;
            
            int result1=PXwon();
            int result2=POwon();
            
            if(result1==1)
            {
                JOptionPane.showConfirmDialog(rootPane, "Nguoi choi X thang !! ");
            }
            else if(result2==1) 
            {
                JOptionPane.showConfirmDialog(rootPane, "Nguoi choi O thang !! ");
            }
        }
        else 
        {
            turn++;
            b6.setText("0");
            buttonused[6]=1;
            POwon[6]=1;
            
            int result1=PXwon();
            int result2=POwon();
            
            if(result1==1)
            {
                JOptionPane.showConfirmDialog(rootPane, "Nguoi choi X thang !! ");
            }
            else if(result2==1) 
            {
                JOptionPane.showConfirmDialog(rootPane, "Nguoi choi O thang !! ");
            }
        }
}


        else{
                JOptionPane.showConfirmDialog(rootPane, "Nút Này Đã sử dụng rồi !!");
                }
    }//GEN-LAST:event_b6ActionPerformed

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
        if(buttonused[7]==0){
            
        
        if(turn %2 == 0)
        {
            turn++;
            b7.setText("x");
            buttonused[7]=1;
            PXwon[7]=1;
            
            int result1=PXwon();
            int result2=POwon();
            
            if(result1==1)
            {
                JOptionPane.showConfirmDialog(rootPane, "Nguoi choi X thang !! ");
            }
            else if(result2==1) 
            {
                JOptionPane.showConfirmDialog(rootPane, "Nguoi choi O thang !! ");
            }
        }
        else 
        {
            turn++;
            b7.setText("0");
            buttonused[7]=1;
            POwon[7]=1;
            
            int result1=PXwon();
            int result2=POwon();
            
            if(result1==1)
            {
                JOptionPane.showConfirmDialog(rootPane, "Nguoi choi X thang !! ");
            }
            else if(result2==1) 
            {
                JOptionPane.showConfirmDialog(rootPane, "Nguoi choi O thang !! ");
            }
        }
}


        else{
                JOptionPane.showConfirmDialog(rootPane, "Nút Này Đã sử dụng rồi !!");
                }
    }//GEN-LAST:event_b7ActionPerformed

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8ActionPerformed
        if(buttonused[8]==0){
            
        
        if(turn %2 == 0)
        {
            turn++;
            b8.setText("x");
            buttonused[8]=1;
            PXwon[8]=1;
            
            int result1=PXwon();
            int result2=POwon();
            
            if(result1==1)
            {
                JOptionPane.showConfirmDialog(rootPane, "Nguoi choi X thang !! ");
            }
            else if(result2==1) 
            {
                JOptionPane.showConfirmDialog(rootPane, "Nguoi choi O thang !! ");
            }
        }
        else 
        {
            turn++;
            b8.setText("0");
            buttonused[8]=1;
            POwon[8]=1;
            
            int result1=PXwon();
            int result2=POwon();
            
            if(result1==1)
            {
                JOptionPane.showConfirmDialog(rootPane, "Nguoi choi X thang !! ");
            }
            else if(result2==1) 
            {
                JOptionPane.showConfirmDialog(rootPane, "Nguoi choi O thang !! ");
            }
        }
}


        else{
                JOptionPane.showConfirmDialog(rootPane, "Nút Này Đã sử dụng rồi !!");
                }
    }//GEN-LAST:event_b8ActionPerformed

    private void bnt_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnt_1ActionPerformed
b0.setText("");
b1.setText("");
b2.setText("");
b3.setText("");
b4.setText("");
b5.setText("");
b6.setText("");
b7.setText("");
b8.setText("");

        for (int i = 0; i < 9; i++) 
        {
         buttonused[i]=0;
          POwon[i]=0;
          PXwon[i]=0;
            
        }
        turn=2;
        
    }//GEN-LAST:event_bnt_1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tictacte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tictacte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tictacte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tictacte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tictacte().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b0;
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton bnt_1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
